import { useEffect, useMemo, useState, useCallback } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, Download, CheckSquare, ChevronDown, Clock, Globe, User } from 'lucide-react'
import { api } from '../api'
import { LevelPill, Spinner, ErrorBox, SEV_COLOR } from '../components/ui'
import EventsTable from '../components/EventsTable'
import { fmtTime, fmtDuration, STAGE_LABELS, SEVERITY_INFO } from '../lib/format'

function buildReport(inc, evidenceBySeq) {
  const lines = [
    `# ${inc.title}`,
    '',
    `- Level: **${SEVERITY_INFO[inc.severity].label}** (${inc.severity}, score ${inc.score}/100)`,
    `- When: ${fmtTime(inc.first_seen)} → ${fmtTime(inc.last_seen)} UTC (${fmtDuration(inc.first_seen, inc.last_seen)})`,
    `- From: ${inc.ips.join(', ') || '—'}`,
    `- Accounts: ${inc.users.join(', ') || '—'}`,
    '',
    '## Summary',
    inc.story.summary,
    '',
    '## What happened',
  ]
  inc.alerts.forEach((a, i) => {
    lines.push(`### ${i + 1}. ${a.title}`, `${fmtTime(a.first_seen)} UTC · ${STAGE_LABELS[a.stage]} (${a.stage})`, '', a.description, '', '```')
    for (const seq of a.evidence.slice(0, 15)) {
      const e = evidenceBySeq.get(seq)
      if (e) lines.push(e.raw)
    }
    if (a.evidence.length > 15) lines.push(`... ${a.evidence.length - 15} more`)
    lines.push('```', '')
  })
  lines.push('## What to do now', ...inc.story.recommendations.map((r) => `- [ ] ${r}`), '', '_Generated by LogHound_')
  return lines.join('\n')
}

export default function Incident() {
  const { id, ref } = useParams()
  const [inc, setInc] = useState(null)
  const [error, setError] = useState(null)
  const [open, setOpen] = useState(() => new Set())

  const load = useCallback(() => {
    setError(null)
    api.getIncident(id, ref).then(setInc).catch(setError)
  }, [id, ref])
  useEffect(load, [load])

  const evidenceBySeq = useMemo(() => new Map((inc?.evidence || []).map((e) => [e.seq, e])), [inc])

  if (error) return <ErrorBox error={error} onRetry={load} />
  if (!inc) return <Spinner label="Loading…" />

  const toggle = (alertId) =>
    setOpen((prev) => {
      const next = new Set(prev)
      next.has(alertId) ? next.delete(alertId) : next.add(alertId)
      return next
    })

  const download = () => {
    const blob = new Blob([buildReport(inc, evidenceBySeq)], { type: 'text/markdown' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `${inc.ref}-report.md`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  return (
    <div className="mx-auto max-w-5xl space-y-6">
      <Link to={`/analysis/${id}`} className="inline-flex items-center gap-1 text-sm text-muted hover:text-white">
        <ArrowLeft className="h-4 w-4" /> Back to results
      </Link>

      <header className="panel p-5" style={{ borderTop: `4px solid ${SEV_COLOR[inc.severity]}` }}>
        <div className="flex flex-wrap items-center gap-3">
          <LevelPill severity={inc.severity} />
          <span className="text-sm text-muted">{SEVERITY_INFO[inc.severity].hint}</span>
        </div>
        <h1 className="mt-3 text-2xl font-semibold text-white md:text-3xl">{inc.title}</h1>
        <p className="mt-3 max-w-3xl text-[15px] leading-relaxed text-slate-300">{inc.story.summary}</p>

        <dl className="mt-5 grid gap-3 text-sm sm:grid-cols-3">
          <div className="rounded-lg bg-panel-2 px-3 py-2">
            <dt className="flex items-center gap-1.5 text-xs text-muted">
              <Clock className="h-3.5 w-3.5" /> When (UTC)
            </dt>
            <dd className="mt-0.5 text-slate-200">
              {fmtTime(inc.first_seen, { seconds: false })} · lasted {fmtDuration(inc.first_seen, inc.last_seen)}
            </dd>
          </div>
          <div className="rounded-lg bg-panel-2 px-3 py-2">
            <dt className="flex items-center gap-1.5 text-xs text-muted">
              <Globe className="h-3.5 w-3.5" /> Came from
            </dt>
            <dd className="mono mt-0.5 text-[13px] text-rose-200">{inc.ips.join(', ') || '—'}</dd>
          </div>
          <div className="rounded-lg bg-panel-2 px-3 py-2">
            <dt className="flex items-center gap-1.5 text-xs text-muted">
              <User className="h-3.5 w-3.5" /> Accounts involved
            </dt>
            <dd className="mono mt-0.5 text-[13px] text-sky-200">{inc.users.join(', ') || '—'}</dd>
          </div>
        </dl>
      </header>

      <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]">
        <section className="min-w-0">
          <h2 className="mb-3 text-lg font-semibold text-white">What happened, step by step</h2>
          <ol className="space-y-3">
            {inc.alerts.map((a, i) => {
              const isOpen = open.has(a.id)
              const evs = a.evidence.map((s) => evidenceBySeq.get(s)).filter(Boolean)
              return (
                <li key={a.id} className="panel overflow-hidden">
                  <div className="flex gap-4 p-4">
                    <div
                      className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-sm font-semibold text-white"
                      style={{ background: SEV_COLOR[a.severity] }}
                    >
                      {i + 1}
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="text-xs text-muted">
                        {fmtTime(a.first_seen)} · <span className="text-slate-300">{STAGE_LABELS[a.stage]}</span>
                      </div>
                      <div className="mt-1 font-medium text-slate-100">{a.title}</div>
                      <div className="mt-1 text-sm text-slate-400">{a.description}</div>
                      <button onClick={() => toggle(a.id)} className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-sky-300 hover:text-sky-200">
                        {isOpen ? 'Hide' : 'Show'} the log lines ({evs.length})
                        <ChevronDown className={`h-3.5 w-3.5 transition ${isOpen ? 'rotate-180' : ''}`} />
                      </button>
                    </div>
                  </div>
                  {isOpen && (
                    <div className="border-t border-line bg-black/20">
                      <EventsTable events={evs} />
                    </div>
                  )}
                </li>
              )
            })}
          </ol>
        </section>

        <aside className="space-y-4">
          <div className="panel p-4 lg:sticky lg:top-20">
            <div className="mb-3 flex items-center gap-2 font-semibold text-white">
              <CheckSquare className="h-4 w-4 text-emerald-400" /> What to do now
            </div>
            <ol className="space-y-3 text-sm text-slate-300">
              {inc.story.recommendations.map((r, i) => (
                <li key={i} className="flex gap-2">
                  <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-emerald-500/15 text-[11px] font-semibold text-emerald-300">
                    {i + 1}
                  </span>
                  <span>{r}</span>
                </li>
              ))}
            </ol>
            <button className="btn-ghost mt-4 w-full" onClick={download}>
              <Download className="h-4 w-4" /> Download report
            </button>
          </div>
        </aside>
      </div>
    </div>
  )
}
