import { useEffect, useMemo, useState, useCallback } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, Download, ShieldCheck, ChevronDown, Clock, ListTree } from 'lucide-react'
import { api } from '../api'
import { SeverityBadge, ScoreBar, Chip, StageChain, Spinner, ErrorBox, SEV_COLOR } from '../components/ui'
import EventsTable from '../components/EventsTable'
import { fmtTime, fmtDuration, RULE_LABELS } from '../lib/format'

function buildReport(inc, evidenceBySeq) {
  const lines = [
    `# ${inc.ref}: ${inc.title}`,
    '',
    `- Severity: **${inc.severity}** (score ${inc.score}/100)`,
    `- Window: ${fmtTime(inc.first_seen)} → ${fmtTime(inc.last_seen)} UTC (${fmtDuration(inc.first_seen, inc.last_seen)})`,
    `- IPs: ${inc.ips.join(', ') || '—'}`,
    `- Accounts: ${inc.users.join(', ') || '—'}`,
    `- Stages: ${inc.stages.join(' → ')}`,
    '',
    '## Summary',
    inc.story.summary,
    '',
    '## Timeline',
  ]
  for (const a of inc.alerts) {
    lines.push(`### ${fmtTime(a.first_seen)} · ${a.stage} · ${a.severity}`, a.description, '', '```')
    for (const seq of a.evidence.slice(0, 15)) {
      const e = evidenceBySeq.get(seq)
      if (e) lines.push(e.raw)
    }
    if (a.evidence.length > 15) lines.push(`... ${a.evidence.length - 15} more`)
    lines.push('```', '')
  }
  lines.push('## Recommended actions', ...inc.story.recommendations.map((r) => `- ${r}`), '')
  lines.push('_Generated by LogHound_')
  return lines.join('\n')
}

export default function Incident() {
  const { id, ref } = useParams()
  const [inc, setInc] = useState(null)
  const [error, setError] = useState(null)
  const [open, setOpen] = useState(() => new Set())
  const [view, setView] = useState('timeline')

  const load = useCallback(() => {
    setError(null)
    api.getIncident(id, ref).then(setInc).catch(setError)
  }, [id, ref])
  useEffect(load, [load])

  const evidenceBySeq = useMemo(() => new Map((inc?.evidence || []).map((e) => [e.seq, e])), [inc])

  if (error) return <ErrorBox error={error} onRetry={load} />
  if (!inc) return <Spinner label="Loading incident…" />

  const toggle = (alertId) =>
    setOpen((prev) => {
      const next = new Set(prev)
      next.has(alertId) ? next.delete(alertId) : next.add(alertId)
      return next
    })

  const download = () => {
    const blob = new Blob([buildReport(inc, evidenceBySeq)], { type: 'text/markdown' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `${inc.ref}-report.md`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  return (
    <div className="space-y-6">
      <Link to={`/analysis/${id}`} className="inline-flex items-center gap-1 text-xs text-muted hover:text-white">
        <ArrowLeft className="h-3.5 w-3.5" /> Back to analysis
      </Link>

      <div className="panel p-5" style={{ borderTop: `3px solid ${SEV_COLOR[inc.severity]}` }}>
        <div className="flex flex-wrap items-center gap-3">
          <span className="mono text-muted">{inc.ref}</span>
          <SeverityBadge severity={inc.severity} />
          <ScoreBar score={inc.score} severity={inc.severity} />
          <span className="inline-flex items-center gap-1 text-xs text-muted">
            <Clock className="h-3.5 w-3.5" />
            {fmtTime(inc.first_seen)} → {fmtTime(inc.last_seen, { date: false })} UTC · {fmtDuration(inc.first_seen, inc.last_seen)}
          </span>
          <button className="btn-ghost ml-auto px-3 py-1.5" onClick={download}>
            <Download className="h-4 w-4" /> Export report
          </button>
        </div>
        <h1 className="mt-3 text-2xl font-semibold text-white">{inc.title}</h1>
        <p className="mt-2 max-w-4xl leading-relaxed text-slate-300">{inc.story.summary}</p>
        <div className="mt-4 flex flex-wrap gap-2">
          {inc.ips.map((ip) => (
            <Link key={ip} to={`/analysis/${id}?tab=events&ip=${encodeURIComponent(ip)}`}>
              <Chip tone="ip">IP · {ip}</Chip>
            </Link>
          ))}
          {inc.users.map((u) => (
            <Link key={u} to={`/analysis/${id}?tab=events&user=${encodeURIComponent(u)}`}>
              <Chip tone="user">user · {u}</Chip>
            </Link>
          ))}
        </div>
        <div className="mt-5 border-t border-line pt-4">
          <div className="mb-2 text-xs uppercase tracking-wider text-muted">Attack progression</div>
          <StageChain stages={inc.stages} />
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
        <div className="min-w-0">
          <div className="mb-3 flex items-center gap-1">
            {[
              ['timeline', 'Incident timeline', Clock],
              ['evidence', `All evidence (${inc.evidence.length})`, ListTree],
            ].map(([v, label, Icon]) => (
              <button
                key={v}
                onClick={() => setView(v)}
                className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm ${view === v ? 'bg-panel-2 text-white' : 'text-muted hover:text-slate-200'}`}
              >
                <Icon className="h-4 w-4" /> {label}
              </button>
            ))}
          </div>

          {view === 'timeline' ? (
            <ol className="relative ml-3 border-l border-line">
              {inc.alerts.map((a) => {
                const isOpen = open.has(a.id)
                const evs = a.evidence.map((s) => evidenceBySeq.get(s)).filter(Boolean)
                return (
                  <li key={a.id} className="relative mb-4 pl-6">
                    <span
                      className="absolute -left-[7px] top-4 h-3.5 w-3.5 rounded-full ring-4 ring-bg"
                      style={{ background: SEV_COLOR[a.severity] }}
                    />
                    <div className="panel overflow-hidden">
                      <button onClick={() => toggle(a.id)} className="w-full p-4 text-left hover:bg-panel-2/50">
                        <div className="flex flex-wrap items-center gap-2 text-xs">
                          <span className="mono text-slate-400">{fmtTime(a.first_seen)}</span>
                          <span className="rounded bg-rose-500/15 px-1.5 py-0.5 font-medium text-rose-200">{a.stage}</span>
                          <SeverityBadge severity={a.severity} />
                          <span className="text-muted">{RULE_LABELS[a.rule] || a.rule}</span>
                          <span className="ml-auto inline-flex items-center gap-1 text-muted">
                            {a.meta?.eventCount ?? evs.length} event{(a.meta?.eventCount ?? evs.length) === 1 ? '' : 's'}
                            <ChevronDown className={`h-4 w-4 transition ${isOpen ? 'rotate-180' : ''}`} />
                          </span>
                        </div>
                        <div className="mt-2 font-medium text-slate-100">{a.title}</div>
                        <div className="mt-1 text-sm text-muted">{a.description}</div>
                      </button>
                      {isOpen && (
                        <div className="border-t border-line bg-black/20">
                          <EventsTable events={evs} />
                          {a.meta?.eventCount > evs.length && (
                            <div className="px-4 py-2 text-xs text-muted">
                              Showing {evs.length} of {a.meta.eventCount} events.{' '}
                              <Link className="text-sky-300 hover:underline" to={`/analysis/${id}?tab=events&${a.entity_type === 'ip' ? 'ip' : 'user'}=${encodeURIComponent(a.entity)}`}>
                                See all events for {a.entity}
                              </Link>
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  </li>
                )
              })}
            </ol>
          ) : (
            <div className="panel">
              <EventsTable events={inc.evidence} />
            </div>
          )}
        </div>

        <aside className="space-y-4">
          <div className="panel p-4">
            <div className="mb-3 flex items-center gap-2 text-sm font-medium text-slate-200">
              <ShieldCheck className="h-4 w-4 text-emerald-400" /> Recommended actions
            </div>
            <ol className="space-y-2.5 text-sm text-slate-300">
              {inc.story.recommendations.map((r, i) => (
                <li key={i} className="flex gap-2">
                  <span className="mono mt-0.5 text-muted">{i + 1}.</span>
                  <span>{r}</span>
                </li>
              ))}
            </ol>
          </div>
          <div className="panel p-4 text-xs leading-relaxed text-muted">
            <div className="mb-1 font-medium text-slate-300">How this incident was built</div>
            Alerts are linked when they share an IP or account, or when a flagged IP successfully logged in as an account. The score starts from the strongest
            alert and goes up for every extra attack stage reached, so a chain like brute force → login → privilege escalation ranks above a failed brute force.
          </div>
        </aside>
      </div>
    </div>
  )
}
